---
title: "Project2-1"
author: "Cecilia De La Fuente Chavez"
format: html
execute:
  echo: true
editor: visual
---

## Approach Deliverable

### Overview

The first dataset I chose for Project 2 is a [table from Wikipedia comparing greenhouse gas emissions associated with charging plug-in electric vehicles in different U.S. cities](https://en.wikipedia.org/wiki/Plug-in_electric_vehicles_in_the_United_States#cite_ref-UCS2012EVs_112-0). The data comes from a Union of Concerned Scientists study. Although this is not a “wide” dataset, it is an example of untidy data. The table contains hierarchical and grouped information. The cities are grouped into categories such as “Best,” “Better,” and “Good,” but these categories are presented as section headings rather than as a variable for each city. Some rows contain city data, while other rows contain additional headings such as “Tailpipe CO2” and “Upstream GHG.” This makes it difficult to treat each row as a consistent observation with the same variables. I will restructure the data so that each city is represented through each variable stored in its own column. For the analysis, I could answer the question: "How do the greenhouse gas emissions associated with plug-in electric vehicles vary across U.S. cities?"
